SELECT PROD.NAME, PROV.NAME, CAT.NAME 
FROM PRODUCTS PROD
INNER JOIN PROVIDERS PROV
    ON PROD.ID_PROVIDERS = PROV.ID
INNER JOIN CATEGORIES CAT
    ON PROD.ID_CATEGORIES = CAT.ID
WHERE PROV.NAME = 'Sansul SA' AND CAT.NAME = 'Imported'