SELECT PROD.NAME, PROV.NAME, PROD.PRICE 
FROM PRODUCTS PROD
INNER JOIN PROVIDERS PROV
    ON PROD.ID_PROVIDERS = PROV.ID
INNER JOIN CATEGORIES CAT
    ON PROD.ID_CATEGORIES = CAT.ID
WHERE PRICE > 1000 AND CAT.NAME = 'Super Luxury'