SELECT 
    C.NAME, 
    CAST((((S.MATH*2) + (S.SPECIFIC*3) + (S.PROJECT_PLAN * 5)) / 10) AS NUMERIC(15,2)) AS AVG
FROM CANDIDATE C INNER JOIN SCORE S
    ON S.CANDIDATE_ID = C.ID
ORDER BY AVG DESC