SELECT 
    L.NAME, 
    ROUND((L.OMEGA * 1.618) ,3) AS "Fator N"
FROM LIFE_REGISTRY L
INNER JOIN DIMENSIONS D
    ON L.DIMENSIONS_ID = D.ID
WHERE L.NAME LIKE 'Richard%' AND D.NAME IN ('C875', 'C774')
ORDER BY L.OMEGA ASC